services:
  mqtt-broker:
    image: ${MQTT_BROKER_IMAGE:-ghcr.io/pdggrp9/infra-broker:latest}
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      MQTT_USER: ${MQTT_USER:-mqtt}
      MQTT_PASSWORD: ${MQTT_PASSWORD:-mqtt}
    volumes:
      - mqtt-config:/mosquitto/config
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log
  db:
    image: ${DB_IMAGE:-ghcr.io/pdggrp9/infra-db:latest}
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bracelet_connecte}
      POSTGRES_USER: ${POSTGRES_USER:-bracelet}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bracelet}
  backend:
    image: ghcr.io/pdggrp9/webapp-backend:latest
    depends_on:
      - db
      - mqtt-broker
  frontend:
    image: ghcr.io/pdggrp9/webapp-frontend:latest
    ports:
      - "3000:80"

volumes:
  mqtt-config:
  mqtt-data:
  mqtt-log:
  db-data: